#!/usr/bin/env bash

CONFIG="$HOME/.config/rofi/config.rasi"

# Run
rofi \
  -show drun \
  -modi drun,run \
	-no-lazy-grab \
	-scroll-method 0 \
	-drun-match-fields all \
	-drun-display-format "{name}" \
	-no-drun-show-actions \
  -kb-cancel Super+d \
  -terminal alacritty \
	-theme ${CONFIG}
