#!/usr/bin/env bash

## Setting environment variables for wayland session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=hyprland
export XDG_CURRENT_DESKTOP=hyprland
export XDG_CURRENT_SESSION=hyprland

## Nvidia variables
export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export WLR_NO_HARDWARE_CURSORS=1
export WLR_BACKEND=vulkan

## GTK environment
export TDESKTOP_DISABLE_GTK_INTEGRATION=1
export CLUTTER_BACKEND=wayland
export BEMENU_BACKEND=wayland
export GDK_BACKEND=wayland
#export GDK_SCALE=1.8
#export GDK_DPI_SCALE=1.6

## Qt environment
export QT_QPA_PLATFORM="wayland;xcb"
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_SCALE_FACTOR=1
export QT_FONT_DPI=165 clementine
export QT_QPA_PLATFORMTHEME=qt5ct

## Elementary environment
export ELM_DISPLAY=wl
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export ELM_ACCEL=opengl
export ELM_SCALE=1.5

## SDL environment
export SDL_VIDEODRIVER=wayland

## Shell Environment
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export PATH=$HOME/.config/emacs/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=/root/.local/bin:$PATH

export EDITOR="nvim"
export TERMINAL="foot"
export BROWSER="firefox"

## Kitty environment
export KITTY_ENABLE_WAYLAND=1

## Mozilla environment
export MOZ_ENABLE_WAYLAND=1

## Java environment
export _JAVA_AWT_WM_NONREPARENTING=1

## Start Hyprland
Hyprland
