#!/usr/bin/env bash

# Kill already running process
_ps=(waybar swayidle swhks polkit-gnome-authentication-agent-1)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# statusbar
hyprbar &

# Idle
hypridle &

# hotkey daemon
hyprkeys &

# wallpaper 
hyprwall &

# theme
hyprtheme &

# polkit 
hyprpolkit &

# pyprland 
pypr &

# Start Apps
ckb-next &
QT_QPA_PLATFORM=xcb insync start &

# avizo
avizo-service
