#!/bin/sh

interval=0

# colors

black=#1E1D2D
green=#ABE9B3
white=#D9E0EE
grey=#282737
blue=#96CDFB
red=#F28FAD
darkblue=#83bae8
mauve=#E0B0FF

volume() {
	vol_icon="$(~/.local/bin/volume)"
  	volume=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master))
  	printf "^c$black^^b$white^ $vol_icon" 
	printf "^c$white^ ^b$grey^ $volume%% ^b$black^" 
}

cpu() {
	cpu_val=$(grep -o "^[^ ]*" /proc/loadavg)
	printf "^c$black^ ^b$green^  "
	printf "^c$white^ ^b$grey^ $cpu_val ^b$black^"
}

pkg_updates() {
  updates=$(checkupdates 2>/dev/null | wc -l) # arch
  if [ -z "$updates" ]; then
    printf "  ^c$green^    Fully Updated"
  else
    printf "  ^c$green^    $updates"" updates"
  fi
}

battery() {
	get_capacity="$(cat /sys/class/power_supply/BAT1/capacity)"
	printf "^c$blue^   $get_capacity"
}

brightness() {
	printf "^c$red^   "
	printf "^c$red^%.0f\n" $(cat /sys/class/backlight/*/brightness)
}

mem() {
	mem=$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)
	printf "^c$blue^^b$black^  "
	printf "^c$white^ ^b$grey^ $mem ^b$black^"
}


clock() {
	printf "\x03^c$black^ ^b$darkblue^ 󱑆 "
	printf "^c$black^^b$blue^ $(date '+%I:%M') ^b$black^"
}

power() {
	printf "\x01^c$black^ ^b$darkblue^ ⭘ "
}

while true; do
  [ $interval = 0 ] || [ $(($interval % 3600)) = 0 ] && updates=$(pkg_updates)
  interval=$((interval + 1))
  sleep 1 && xsetroot -name "$updates $(battery) $(brightness) $(cpu) $(mem) $(volume) $(clock) $(power)"
done
